CREATE TABLE grade(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE position(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE staff(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  card_id VARCHAR(255),
  name VARCHAR(50) NOT NULL,
  grade INT REFERENCES grade(id),
  position INT REFERENCES position(id),
  phone VARCHAR(50),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE student(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  card_id VARCHAR(255),
  name VARCHAR(50) NOT NULL,
  gender SMALLINT,
  grade INT REFERENCES grade(id),
  address VARCHAR(255),
  avatar VARCHAR(255),
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE parent(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  card_id VARCHAR(255),
  name VARCHAR(50) NOT NULL,
  role VARCHAR(50) NOT NULL,
  avatar VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  student BIGINT REFERENCES student(id) on delete cascade
);

CREATE TABLE record(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  card_id VARCHAR(255),
  video VARCHAR(255),
  in_out INT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);


CREATE TABLE hot_words(
  id bigserial NOT NULL PRIMARY KEY,
  word VARCHAR(255) NOT NULL
);
